### ISSUE TITLE
Add theme

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-Programs#112]
I have added a [theme](https://github.com/tapaswenipathak/Theme).

- Install using `npm i list-theme`.
- Add the information present in [index.html](https://github.com/tapaswenipathak/Open-Source-Internships/blob/master/index.html) in the theme's [index.html](https://github.com/tapaswenipathak/Theme/blob/master/index.html#L6-L42) 
- Deploy on a Heroku App.
- Create a PR.
- Add the deployed app link.
- Take the credentials from me.
- Deploy in my Heroku account.

**Comment by prondubuisi** [comment]
@tapaswenipathak I would love to work on this

**Comment by tapaswenipathak** [comment]
Sure, go for it!

**Comment by prondubuisi** [comment]
So `npm i list-theme
`
returns a 404 error can 
https://registry.npmjs.org/list-theme
@tapaswenipathak

**Comment by tapaswenipathak** [comment]
I didn't publish the code. Run `npm install && npm link`. You can put the code in the repository without installing anything as well.

**Comment by parulagg27** [comment]
Can I work on this issue, @tapaswenipathak?

**Comment by tapaswenipathak** [comment]
On Fri, May 10, 2019 at 2:06 PM Parul <notifications@github.com> wrote:
>
> Can I work on this issue, @tapaswenipathak?

Sure!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by parulagg27** [comment]
Alright! Working on this one.

**Comment by parulagg27** [comment]
Alright! Working on this one.
