### ISSUE TITLE
Add pr template 

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-Programs#125]
Any addition should be written in index.html.

**Comment by prondubuisi** [comment]
Hello @tapaswenipathak I am confused on what this issue is about

**Comment by tapaswenipathak** [comment]
On Sat, May 11, 2019 at 11:35 AM Onyemenam Ndubuisi
<notifications@github.com> wrote:
>
> Hello @tapaswenipathak I am confused on what this issue is about

PR template should have

 -
- [ ] You have added the SoC/WoC in README.md file in correct table
- [ ] You have added the SoC/WoC in index.html in correct table
- [ ] Website tested on a deployment

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by prateekj117** [comment]
@tapaswenipathak I think we can close this issue.
