### ISSUE TITLE
Create an OSI badge

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-Programs#133]
I was working on an open source project and found https://shields.io is great for creating badges. 

Sample https://shields.io/category/version.

**Comment by shreyateeza** [comment]
I would like to work on this issue.

**Comment by tapaswenipathak** [comment]
On Tue, May 14, 2019 at 11:34 AM Shreya <notifications@github.com> wrote:
>
> I would like to work on this issue.

Sure!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by Naba7** [comment]
Can I work on this?
