### ISSUE TITLE
Tweag I/O summer internship

### ISSUE THREAD

**Issue by je117er** [tapaswenipathak/Open-Source-Programs#146]
This is a 2 or 3 month summer internship from [Tweag I/O](https://www.tweag.io/posts/2019-03-11-internships.html) for students with the opportunity to do it remotely (apart from doing onsite in Paris) with a payment scale similar to that of GSoC.

**Comment by shubhank-saxena** [comment]
@je117er it's no longer accepting entries.

**Comment by je117er** [comment]
> @je117er it's no longer accepting entries.
You mean the internship? I thought it might reopen next year so it's worth adding it here.

From the internship landing page:
>The time has come again to invite applications for Tweag I/O's paid internship programme this summer.

**Comment by emetowinner** [comment]
i think this issue should be closed
