### ISSUE TITLE
Add https://www.pclubsummerofcode.in/

### ISSUE THREAD

**Issue by tharun143** [tapaswenipathak/Open-Source-Programs#197]
Programming Club UIET or PCIub for short is a student driven society that aims af educating students about various domains of Computer Science, Electronics and Technology.

[Pclub](https://www.pclubsummerofcode.in/)

**Comment by deepanshu1422** [comment]
Please post your PR's on https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs as this current repository is not merging any pull request since November 2019
