### ISSUE TITLE
Kharagpur Open Source Society

### ISSUE THREAD

**Issue by bprakashputta** [tapaswenipathak/Open-Source-Programs#202]
The link to the Kharagpur Open Society is not working, I would like you to update the link

[]()
https://kossiitkgp.org/

**Comment by AdityaGupta150** [comment]
> 
> 
> The link to the Kharagpur Open Society is not working, I would like you to update the link
> 
> 
> https://kossiitkgp.org/

It is am open source society, of a group of people working on open source projects, but i couldn't find they hold a summer of code or winter of code ? Do they have a summer of code?

**Comment by bhanu3509** [comment]
Actually they used to have one but it hasn't happened last year for reasons unknown and they have removed it now. They used to have a winter of code from December to January, for a duration of one month.

**Comment by mukul-mehta** [comment]
Hey! I'm a member of KOSS and we still have KWoC every winter. The website has moved, probably leading to the confusion
KOSS Website: https://kossiitkgp.org/
KWoC Website: http://kwoc.kossiitkgp.org/
